# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Remote.ui'
#
# Created: Thu Dec 24 02:32:27 2009
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(766, 450)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(96, 96, 96))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 101, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 76, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(96, 96, 96))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 101, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 76, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(96, 96, 96))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(199, 199, 199))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 101, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 101, 91))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 76, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        Frame.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../usr/share/pixmaps/rhythmbox.xpm"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Frame.setWindowIcon(icon)
        Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.gridLayout = QtGui.QGridLayout(Frame)
        self.gridLayout.setObjectName("gridLayout")
        self.current = QtGui.QLabel(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.current.sizePolicy().hasHeightForWidth())
        self.current.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.current.setFont(font)
        self.current.setTextFormat(QtCore.Qt.PlainText)
        self.current.setObjectName("current")
        self.gridLayout.addWidget(self.current, 0, 0, 1, 7)
        self.slider = QtGui.QSlider(Frame)
        self.slider.setOrientation(QtCore.Qt.Horizontal)
        self.slider.setObjectName("slider")
        self.gridLayout.addWidget(self.slider, 3, 0, 1, 7)
        self.list = QtGui.QListWidget(Frame)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.list.setFont(font)
        self.list.setAlternatingRowColors(True)
        self.list.setObjectName("list")
        self.gridLayout.addWidget(self.list, 4, 0, 1, 7)
        self.filter = QtGui.QLineEdit(Frame)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.filter.setFont(font)
        self.filter.setObjectName("filter")
        self.gridLayout.addWidget(self.filter, 5, 0, 1, 7)
        self.previous = QtGui.QToolButton(Frame)
        self.previous.setObjectName("previous")
        self.gridLayout.addWidget(self.previous, 1, 0, 1, 1)
        self.play = QtGui.QToolButton(Frame)
        self.play.setObjectName("play")
        self.gridLayout.addWidget(self.play, 1, 1, 1, 1)
        self.next = QtGui.QToolButton(Frame)
        self.next.setObjectName("next")
        self.gridLayout.addWidget(self.next, 1, 2, 1, 1)
        self.stop = QtGui.QPushButton(Frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.stop.setFont(font)
        self.stop.setObjectName("stop")
        self.gridLayout.addWidget(self.stop, 1, 3, 1, 1)
        self.fullscreen = QtGui.QPushButton(Frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.fullscreen.setFont(font)
        self.fullscreen.setObjectName("fullscreen")
        self.gridLayout.addWidget(self.fullscreen, 1, 4, 1, 1)
        self.mark = QtGui.QPushButton(Frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.mark.setFont(font)
        self.mark.setObjectName("mark")
        self.gridLayout.addWidget(self.mark, 1, 5, 1, 1)
        self.load_cd = QtGui.QPushButton(Frame)
        self.load_cd.setObjectName("load_cd")
        self.gridLayout.addWidget(self.load_cd, 1, 6, 1, 1)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(QtGui.QApplication.translate("Frame", "Control remoto", None, QtGui.QApplication.UnicodeUTF8))
        self.current.setText(QtGui.QApplication.translate("Frame", "Ninguno", None, QtGui.QApplication.UnicodeUTF8))
        self.list.setSortingEnabled(True)
        self.previous.setText(QtGui.QApplication.translate("Frame", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.play.setText(QtGui.QApplication.translate("Frame", "II", None, QtGui.QApplication.UnicodeUTF8))
        self.next.setText(QtGui.QApplication.translate("Frame", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.stop.setText(QtGui.QApplication.translate("Frame", "Parar", None, QtGui.QApplication.UnicodeUTF8))
        self.fullscreen.setText(QtGui.QApplication.translate("Frame", "Pantalla Completa", None, QtGui.QApplication.UnicodeUTF8))
        self.mark.setText(QtGui.QApplication.translate("Frame", "Marcar", None, QtGui.QApplication.UnicodeUTF8))
        self.load_cd.setText(QtGui.QApplication.translate("Frame", "Carga CD", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Frame = QtGui.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())

